Flush queues on collector shutdown
GoogleCloudPlatform/prometheus-engine pull request #125
Opened 2022-01-18 16:24 UTC by maxamins

1. When shutdown is initiated stop more messages from being sent
2. Drain the shards and send the batches in under 15 seconds

2022-03-24 13:45 UTC, pintohutch commented
What's the status on this PR?

2022-05-25 15:44 UTC, macxamin commented on pkg/export/export.go
> +		level.Info(e.logger).Log("msg", "Exiting Exporter - will attempt to send remaining data in the next 15 seconds.")
This gets printed twice. Any reason why?

2022-05-25 15:45 UTC, macxamin commented on pkg/export/export_test.go
> +	for i := 0; i < 50; i++ {
Maxes out on 2048 samples. I'm assuming because they only go to one shard. Do you know how to create the shard in a different way?

2023-06-29 17:28 UTC, pintohutch commented
Aside from rebasing - we'll want to benchmark this change to catch any performance regressions - cc @saketjajoo

2024-09-23 19:51 UTC, ridwanmsharif commented
/prombench

2024-10-03 18:19 UTC, ridwanmsharif commented
@pintohutch @bwplotka PTAL, there is https://github.com/GoogleCloudPlatform/prometheus/pull/203 that has some benchmarking results but spoilers: there is no discernible change in performance - which makes sense cause this is exclusively only run on shutdown.

2024-10-03 21:33 UTC, pintohutch commented
That's great to hear! I'll defer to @bwplotka as the SME to review.

2024-10-07 11:04 UTC, bwplotka commented on pkg/export/export.go
> +	flushTimeout = 100 * time.Millisecond
is 100ms making any difference?

2024-10-07 11:07 UTC, bwplotka commented on pkg/export/export.go
> +			// on termination, try to drain the remaining shards within the CancelTimeout.
```suggestion
			// On termination, try to drain the remaining shards within the CancelTimeout.
```

2024-10-07 11:19 UTC, bwplotka commented on pkg/export/export.go
>  		// NOTE(freinartz): we will terminate once context is cancelled and not flush remaining
Let's update this commentary, it's incorrect with the new logic 🤗

2024-10-07 11:20 UTC, bwplotka commented on pkg/export/export.go
> +	drainShardsBeforeExiting := func() {
nit: Not a must, but it might be easier to iterate on if we move `send` and `drain` to separate `Exporter` private methods 🤔

2024-10-07 11:32 UTC, bwplotka requested changes
Thanks! 

Some suggestions  might require some work, so let me know if this is something you have time to do, or we accept some imperfection/code spaghetti.

The main issue is to me with proceeding on send work despite reusing e.ctx which was cancelled already. 🤔

2024-10-07 11:32 UTC, bwplotka commented on pkg/export/export.go
> +			drainShardsBeforeExiting()
Are we sure this works? All sends normally take `e.ctx` context, so they will be cancelled? I assume here you (intentionally?) accept that and drain the buffer with new sends with a separate context.

Would it be cleaner to have a custom, separate context from the beginning?  🤔

2024-10-07 11:32 UTC, bwplotka commented on pkg/export/export.go
> +					// NOTE(ridwanmsharif): the sending of the batches happen asyncronously
Yea, can we improve this? And get that result state from send (or create separate send?)

2024-10-07 11:32 UTC, bwplotka commented on pkg/export/export.go
> +		for {
I would suggest we don't do another goroutine and we do all in this for loop? `Send` is async anyway?

2024-10-07 11:32 UTC, bwplotka commented on pkg/export/export.go
> +		gcmExportCalledWhileDisabled.Inc()
That's unrelated to the main PR goal, I see Max did this, let's at least update description.

2024-10-07 11:32 UTC, bwplotka commented on pkg/export/export.go
> +			e.exitc <- struct{}{}
Ideally we don't have testing specific code in critical, production flow. However, IF we make sure sending propagates some results to us back, we could have a nice production logic that emits log line telling us all was flushed successfully, can we do this?

2024-10-07 11:32 UTC, bwplotka commented on pkg/export/export.go
> +			drainShardsBeforeExiting()
in fact we always use e.ctx even in drain if I look correctly, are we use this code works? 🤔

2025-02-13 12:17 UTC, closed without merging