Bump kube-state-metrics to 2.3.0 and add missing labels
GoogleCloudPlatform/prometheus-engine pull request #283
Opened 2022-07-21 22:46 UTC by ajayk

-  version [2.3.0](https://github.com/kubernetes/kube-state-metrics/blob/e52d8ace1fae43248f225cd27a9bcc90296d6a01/README.md) has pretty good support from k8s1.19 to 1.23 

- Bump nodeexporter to 1.3.1 and minor deprecated flag change

2022-07-21 22:48 UTC, ajayk commented
@lyanco @damemi  for review

2022-07-22 13:15 UTC, damemi requested changes

2022-07-22 13:15 UTC, damemi commented on examples/kube-state-metrics.yaml
> +    interval: 60s
nit: newline at end of file

2022-07-22 13:15 UTC, damemi commented on examples/node-exporter.yaml
> +    interval: 30s
same nit

2022-07-22 16:54 UTC, ajayk commented on examples/kube-state-metrics.yaml
> +    interval: 60s
addressed in the latest commit

2022-07-22 16:54 UTC, ajayk commented on examples/node-exporter.yaml
> +    interval: 30s
addressed in the latest commit

2022-07-25 15:03 UTC, damemi approved these changes

2022-07-27 18:25 UTC, damemi commented
@ajayk can you use `git rebase` to sync with main rather than pull/merge? Having merge commits in the PR gets a bit messy

2022-07-27 20:12 UTC, ajayk commented
@damemi  rebased  , i totally missed it

2022-07-27 20:38 UTC, merged