Require interval for ScrapeEndpoint
GoogleCloudPlatform/prometheus-engine pull request #492
Opened 2023-06-16 17:32 UTC by bernot-dev

Fix #491

2023-06-20 19:10 UTC, StevenYCChou requested changes

2023-06-20 19:10 UTC, StevenYCChou commented on pkg/operator/apis/monitoring/v1/types.go
Can you add tests to the corresponding path pkg/operator/apis/monitoring/v1/types_test.go on the default value and maybe a simple smoke test for the validation pattern?

2023-06-20 19:10 UTC, StevenYCChou commented on pkg/operator/generated/clientset/versioned/clientset.go
Are the code under `pkg/operator/generated/clientset/versioned/clientset.go` generated based on the changes in  `pkg/operator/apis/monitoring/v1/types.go` and you didn't manually write any code here? If that's the case, please just resolve this comment.

2023-06-20 19:25 UTC, bwplotka reviewed
Thanks! 

I think I am fine with types.go and yaml changes, but clientset and factory changes feels unrelated? 🤔 Maybe some different generator version? Should we change that in separate PR?

2023-06-20 19:25 UTC, bwplotka commented on cmd/operator/deploy/crds/monitoring.googleapis.com_clusterpodmonitorings.yaml
> +                      pattern: ^((([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?|0)$
<img src="https://media0.giphy.com/media/b8RfbQFaOs1rO10ren/giphy.gif"/>

2023-06-20 19:25 UTC, bwplotka commented on pkg/operator/generated/clientset/versioned/clientset.go
Yea I think it feels like not releated changes to the main focus of this PR 🤔

2023-06-20 21:13 UTC, bernot-dev commented
> clientset and factory changes feels unrelated? 🤔 Maybe some different generator version? Should we change that in separate PR?

From what I can tell, those files are related somehow...the clientset/factory generated files don't change when I run `make regen` before adding the annotations. Exactly how the generated files are related to the actual change I made is beyond me. But it doesn't seem like the code generator thinks they are unrelated.

2023-06-20 22:16 UTC, StevenYCChou commented on pkg/operator/apis/monitoring/v1/types.go
[bernot-dev](https://github.com/bernot-dev) reached out to me offline that we probably need to add a e2e test running on KIND, not `pkg/operator/apis/monitoring/v1/types_test.go` - and I agree as the change is on the `apiextensions.k8s.io/v1`. 

Thanks for bringing this up, Adam!

2023-06-21 16:09 UTC, bernot-dev commented
@bwplotka You were right, it was skipping codegen when it didn't see that the files had been updated. #497 updates the clientset and factory generated files separately.

2023-06-21 17:03 UTC, bwplotka commented
So this PR has to be rebased now, right?

2023-06-21 17:59 UTC, bwplotka approved these changes
Thanks 💪🏽

2023-06-21 18:09 UTC, merged