Add mTLS support into the example app
GoogleCloudPlatform/prometheus-engine pull request #570
Opened 2023-09-15 18:10 UTC by TheSpiritXIII

Example usage:
```bash
go run ./examples/instrumentation/go-synthetic/ --tls-create-self-signed=true
curl -k https://localhost:8080/metrics
```

This PR builds on top of #569.

2023-09-22 13:07 UTC, bwplotka requested changes
LGTM, thanks!

Just error handling is off.

2023-09-22 13:07 UTC, bwplotka commented on examples/instrumentation/go-synthetic/auth.go
> +			log.Println("Unable to marshal private key", err)
That's a bit odd, let's return error with wrap?

2023-09-22 13:07 UTC, bwplotka commented on examples/instrumentation/go-synthetic/auth.go
> +			log.Println("Unable to marshal private key", err)
same below

2023-09-22 14:14 UTC, macxamin reviewed
LGTM

2023-09-22 14:14 UTC, macxamin commented on examples/instrumentation/go-synthetic/main.go
> +				fmt.Printf("Starting server on %q with TLS\n", *addr)
nit log.Println seems to be used in this file. Should we keep the standard?

2023-09-22 14:14 UTC, macxamin commented on examples/instrumentation/go-synthetic/main.go
> +			fmt.Printf("Starting server on %q\n", *addr)
nit same as above

2023-09-22 14:49 UTC, macxamin approved these changes
LGTM

2023-09-25 12:05 UTC, bwplotka approved these changes
Thanks!

2023-09-25 12:05 UTC, merged