chore: upgrade controller-runtime
GoogleCloudPlatform/prometheus-engine pull request #666
Opened 2023-11-15 20:27 UTC by bernot-dev

Upgrade controller-runtime to v0.15.x

This will unblock #663, as previous versions of controller-runtime do not correctly support providing your own `GetCertificate` method to provide certs.

2023-11-16 20:21 UTC, bernot-dev commented
@TheSpiritXIII #669 may resolve the `validate` check failure. Unit test failures still need to be debugged.

2023-11-27 14:11 UTC, TheSpiritXIII requested changes
Thanks for the good work!

2023-11-27 14:17 UTC, bernot-dev commented on e2e/authorization_test.go
> -	t.Parallel()
This test was passing for me locally when the Parallel was removed. But apparently it doesn't work in CI.

2023-12-01 21:03 UTC, TheSpiritXIII approved these changes
LGTM! Thanks!

2023-12-01 21:22 UTC, merged