feat: [kubelet/cAdvisor metrics package] add NodeMonitoring Status support
GoogleCloudPlatform/prometheus-engine pull request #749
Opened 2024-01-03 22:56 UTC by macxamin

2024-01-03 22:57 UTC, macxamin commented on pkg/operator/collection.go
> +			var scrapeEndpoints []monitoringv1.ScrapeEndpoint
Do you have any better ideas on how to use NodeMonitoringCRD and PodMonitoringCRD in statusUpdates?

2024-01-04 01:12 UTC, TheSpiritXIII requested changes
Just a few nits and an issue to look at. Great job otherwise!

2024-01-04 01:12 UTC, TheSpiritXIII commented on pkg/operator/apis/monitoring/v1/types_test.go
> +		curr, want *MonitoringStatus
nit: maybe also rename function (remove the `Pod` prefix)?

2024-01-04 01:12 UTC, TheSpiritXIII commented on pkg/operator/collection.go
> +			r.statusUpdates = append(r.statusUpdates, &nodeMonConv)
issue: I'm not sure if this is right. `statusUpdates` is for updating statuses of _existing_ [Cluster]PodMonitorings but one doesn't exist here. I believe your intention was to pass the NodeMonitoring object here.  An e2e test would have caught this.

I would rename `PodMonitoringCRD.GetStatus` to something like `PodMonitoringCRD.GetPodMonitoringStatus` and create a new interface with a method `MonitoringCRD.GetStatus` that returns a `MonitoringStatus`. Then, `statusUpdates` can store a `MonitoringCRD` and you'd be able to pass in your `NodeMonitoring` here.

2024-01-18 05:57 UTC, macxamin commented
Closing, this is no longer relevant after the types.go split and https://github.com/GoogleCloudPlatform/prometheus-engine/pull/771.

2024-01-18 05:57 UTC, closed without merging